### PR TITLE
Fixes #873: improve Bean Validation failure messages

### LINKED ISSUE #873: Unclear error message for Bean Validation failures
Annotation-based (Bean Validation) input validation is convenient way to add constraints to REST endpoints, but currently produces error messages that are unclear. User reported:

```
{"errors":[{"message":"Request invalid, the field postCommand.command.name not valid: must match \"[a-zA-Z][a-zA-Z0-9_]*\".","exceptionClass":"ConstraintViolationException"}]}
```

where it is unclear what exactly is wrong. This is produced by `ConstraintViolationExceptionMapper` and:

1. Does not enclose `postCommand.command.name` (which is logical name of property for which value is given) in quotes (to indicate it is specific term), but more importantly
2. Does not actually include problematic value in error message

Since (2) is available from `ConstraintViolation`, let's add it, and also wrt (1) add single quotes to make it bit easier to read.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Improves general failure message produced for Bean Validation constraints-validation failures: adds actual value, and improves messages layout slightly.

**Which issue(s) this PR fixes**:
Fixes #873

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/NamespaceResourceIntegrationTest.java [hunk 1]
```diff
@@ -91,10 +91,9 @@ public void invalidNamespaceName() {
           .post(NamespaceResource.BASE_PATH, "7_no_leading_number")
           .then()
           .statusCode(200)
-          .body(
-              "errors[0].message",
-              startsWith("Request invalid, the field postCommand.namespace not valid"))
-          .body("errors[0].exceptionClass", is("ConstraintViolationException"));
+          .body("errors[0].exceptionClass", is("ConstraintViolationException"))
+          .body("errors[0].message", startsWith("Request invalid: field 'namespace' value"))
+          .body("errors[0].message", containsString("value \"7_no_leading_number\" not valid"));
```
Comment (Yuqi-Du) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/NamespaceResourceIntegrationTest.java:96]: This is the major fix right?
nitpick, reason of not combine these two messages into one?

**Review by Yuqi-Du — APPROVED** [review]

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/NamespaceResourceIntegrationTest.java (hunk 1 above)
Comment (tatu-at-datastax) [reply src/test/java/io/stargate/sgv2/jsonapi/api/v1/NamespaceResourceIntegrationTest.java:96]: Right, that is the fix.

And yes, I think I should just combine the parts together since it is covering the whole String anyway.

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:
