### PR TITLE
Fix #875: improve error message by including field name

### LINKED ISSUE #875: Missing `property` name for "too long String" validation failure
Currently validation error for "too long indexed String" does not include name of property that fails: it should, to help users identify the problematic field.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Improves document validation error message(s) by including field name for too-long-string

**Which issue(s) this PR fixes**:
Fixes #875

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java [hunk 1]
```diff
@@ -353,7 +353,7 @@ private void validateValue(String referringPropertyName, JsonNode value) {
       } else if (value.isArray()) {
         validateArrayValue(referringPropertyName, value);
       } else if (value.isTextual()) {
-        validateStringValue(value.textValue());
+        validateStringValue(referringPropertyName, value.textValue());
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java:356]: Need to pass property name for use in validation fail message.

File: src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java [hunk 2]
```diff
@@ -363,12 +363,12 @@ private void validateArrayValue(String referringPropertyName, JsonNode arrayValu
...
           if (arrayValue.size() > limits.maxVectorEmbeddingLength()) {
             throw ErrorCode.SHRED_DOC_LIMIT_VIOLATION.toApiException(
-                "number of elements Vector embedding ('%s') has (%d) exceeds maximum allowed (%d)",
+                "number of elements Vector embedding (field '%s') has (%d) exceeds maximum allowed (%d)",
                 referringPropertyName, arrayValue.size(), limits.maxVectorEmbeddingLength());
           }
         } else {
           throw ErrorCode.SHRED_DOC_LIMIT_VIOLATION.toApiException(
-              "number of elements an indexable Array ('%s') has (%d) exceeds maximum allowed (%d)",
+              "number of elements an indexable Array (field '%s') has (%d) exceeds maximum allowed (%d)",
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java:371]: Was missing this from Array and Object constraints failures: added to make messages more uniform.

**Review by Hazel-Datastax — APPROVED** [review]
LGTM

**Review by jeffreyscarpenter — APPROVED** [review]
Nice improvement

File: src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java [hunk 3]
```diff
@@ -382,7 +382,7 @@ private void validateObjectValue(String referringPropertyName, JsonNode objectVa
       final int propCount = objectValue.size();
       if (propCount > limits.maxObjectProperties()) {
         throw ErrorCode.SHRED_DOC_LIMIT_VIOLATION.toApiException(
-            "number of properties an indexable Object ('%s') has (%d) exceeds maximum allowed (%s)",
+            "number of properties an indexable Object (field '%s') has (%d) exceeds maximum allowed (%s)",
```
Comment (vkarpov15) [inline src/main/java/io/stargate/sgv2/jsonapi/service/shredding/Shredder.java:385]: Minor nitpick but I'd change "field" -> "property" for consistency here, because you already have "number of properties". And likely in the other error messages as well. Occasionally using "field" and "property" interchangeably is fine, but best to stay consistent in the same sentence.

**Review by vkarpov15 — COMMENTED** [review]
LGTM, just one minor suggestion
