### PR TITLE
closes #298: count down latch to be decrease on assertion errors

### LINKED ISSUE #298: Decrease count-down latch on failing concurrency tests

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
Fixes the count down latch now being decreased on failed asserts.. This will never result in a block..

But the exception would be ignored.. Thus I am thinking what the options are:

* [x] catch any exception, set to the `AtomicReference`, after CTL goes to zero iterate over and re-throw any exception?
* [ ] better ideas?

**Which issue(s) this PR fixes**:
Fixes #298

**WARNING: remove serial consistency commit before merging**

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/bridge/executor/QueryExecutor.java [hunk 1]
```diff
@@ -67,8 +67,13 @@ public Uni<QueryOuterClass.ResultSet> executeWrite(QueryOuterClass.Query query)
     QueryOuterClass.Consistency consistency = queriesConfig.consistency().writes();
     QueryOuterClass.ConsistencyValue.Builder consistencyValue =
         QueryOuterClass.ConsistencyValue.newBuilder().setValue(consistency);
+    QueryOuterClass.Consistency serialConsistency = queriesConfig.serialConsistency();
+    QueryOuterClass.ConsistencyValue.Builder serialConsistencyValue =
+        QueryOuterClass.ConsistencyValue.newBuilder().setValue(serialConsistency);
     QueryOuterClass.QueryParameters.Builder params =
-        QueryOuterClass.QueryParameters.newBuilder().setConsistency(consistencyValue);
+        QueryOuterClass.QueryParameters.newBuilder()
```
Comment (maheshrajamani) [inline src/main/java/io/stargate/sgv2/jsonapi/service/bridge/executor/QueryExecutor.java:74]: Do you want to revert the serial consistency change, so it can be done unit test case as suggested in #290 ?

**Review by maheshrajamani — APPROVED** [review]
