### PR TITLE
invalid $ operator use case, INVALID_REQUEST typo fix 

### LINKED ISSUE #798: Invalid filter, misuse of `$` operators
`{
    "find": {
        "filter": {
            "address": {
                "street": {
                    "$in" :["xxx"]
                }
            }
        }
    }
}`
and got the error message:
`{
    "errors": [
        {
            "message": "Unsupported NodeType OBJECT",
            "errorCode": "UNSUPPORTED_FILTER_DATA_TYPE"
        }
    ]
}`

### PR DESCRIPTION
**Pull request by Yuqi-Du**
**What this PR does**:
`{ "find": { "filter": { "address": { "street": { "$in" :["xxx"] } } } } }`
is a misuse of $ operator, if $in is intended here, should be
`{ "find": { "filter": { "address.street":  { "$in" :["xxx"] } } } }`

fix typo: INVALID_REQEST -> INVALID_REQUEST

**Which issue(s) this PR fixes**:
Fixes #798 #796

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCode.java [hunk 1]
```diff
@@ -25,7 +25,7 @@ public enum ErrorCode {
 
   FILTER_FIELDS_LIMIT_VIOLATION("Filter fields size limitation violated"),
 
-  INVALID_REQUST("Request not supported by the data store"),
+  INVALID_REQUEST("Request not supported by the data store"),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCode.java:28]: Good catch!

**Review by tatu-at-datastax — APPROVED** [review]
Looks good: just need to fix one IT wrt `INVALID_REQUEST` value.

**Review by tatu-at-datastax — APPROVED** [review]

**Review by vkarpov15 — APPROVED** [review]
LGTM :+1:
