### PR TITLE
Fix to #790 implementation to ensure ["*"] is accepted as "allow" or "deny" list

### LINKED ISSUE #790: Validate paths used for `indexing` options for `CreateCollection`
Currently the only validation done for indexing options of CreateCollections is to make sure that only one of arrays ("allow", "deny") is non-empty.

But we should be able to further validate that all paths included are valid paths for JSON API, same as we do for paths used for shredding and filtering.

For example, currently user could use:

```json
"indexing" : {
   "deny" : [ "_id", "data*" ]
}
```

expecting `data*` to be regexp used: it won't and we'd take that to refer to hypothetical value like:

```json
{
   "data*" : 42 
}
```

but we do NOT allow such properties to be used (character '*' not allowed in path segments).

Adding validation would prevent users from creating Indexing settings that cannot work as intended.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Improves "createCollection" validation, testing, to ensure single "*" is accepted as expected

**Which issue(s) this PR fixes**:
Fixes #790

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/CreateCollectionIntegrationTest.java [hunk 1]
```diff
@@ -84,79 +76,6 @@ class CreateCollection {
                 }
                 """;
 
-    String createCollectionWithAllowIndexing =
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/CreateCollectionIntegrationTest.java:87]: Moved these to within tests that need them, no need to separate out.

**Review by Hazel-Datastax — APPROVED** [review]
LGTM

**Review by vkarpov15 — COMMENTED** [review]
LGTM
