### PR TITLE
Fix _id field returned for findOneAndReplace and findOneAndUpdate with upsert option

### LINKED ISSUE #416: findOneAndReplace upsert not generating _id
When the `findOneAndReplace` API is called with `upsert` flag set to true, the new document is generated with the given properties in the `replacement` part of the request, but the `_id` is not generated.  In the below example, you could see `_id` and `upsertedId` are not set in the final response.

To replicate the issue;
```http
http: --- request POST http://localhost:8181/v1 
{
  "createNamespace": {
    "name": "testks1"
  }
}

http: --- request POST http://localhost:8181/v1/testks1 
{
  "createCollection": {
    "name": "products",
    "options": null
  }
}

http: --- request POST http://localhost:8181/v1/testks1/products {
  "findOneAndReplace": {
    "filter": {
      "name": "Product 25"
    },
    "replacement": {
      "name": "Product 25",
      "isCertified": false,
      "price": 20
    },
    "options": {
      "upsert": true,
      "returnDocument": "after"
    }
  }
}


http: --- response 200 POST http://localhost:8181/v1/testks1/products 
{
  "data": {
    "document": {
      "_id": null,
      "name": "Product 25",
      "isCertified": false,
      "price": 20
    }
  },
  "status": {
    "matchedCount": 0,
    "modifiedCount": 0,
    "upsertedId": null
  }
}

```

### PR DESCRIPTION
**Pull request by maheshrajamani**
**What this PR does**:
Fix for Issue #416 and #417, replacement PR for #419
**Which issue(s) this PR fixes**:
Fixes #416 and #417

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/model/impl/ReadAndUpdateOperation.java [hunk 1]
```diff
@@ -175,10 +175,11 @@ private Uni<UpdatedDocument> processUpdate(
...
               }
 
-              // otherwise shred
-              JsonNode updatedDocument = documentUpdaterResponse.document();
               final WritableShreddedDocument writableShreddedDocument =
-                  shredder().shred(updatedDocument, readDocument.txnId());
+                  shredder().shred(documentUpdaterResponse.document(), readDocument.txnId());
+
+              // Have to do this because shredder adds _id field to the document if it doesn't exist
+              JsonNode updatedDocument = writableShreddedDocument.docJsonNode();
```
Comment (ivansenic) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/model/impl/ReadAndUpdateOperation.java:182]: Maybe we should improve the shredded document impl and avoid this side effect call?

**Review by ivansenic — COMMENTED** [review]
Don't have much insight into this part of code in order to review.. Maybe PR title should be improved before merging, so we get meaningful messages in the git history..

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/model/impl/ReadAndUpdateOperation.java (hunk 1 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/model/impl/ReadAndUpdateOperation.java:182]: That sounds like a good improvement idea; something that handles insertion and reordering of `_id` before Shredder gets to deal with it.

I'll create a follow-up issue.
