### PR TITLE
closes #350: errorCode and exceptionClass to be reported always with …

### LINKED ISSUE #350: Errors in response
If there is an error thrown during deserialization of commands, response has array of errors as below. The error message in index 0 adds no value. In my opinion it needs to be removed. 
Also the error code is missing on the raised error, in this case expecting `"errorCode" : INVALID_FILTER_EXPRESSION`

`{
    "errors": [
        {
            "message": "$in operator must have at least one value (through reference chain: io.stargate.sgv2.jsonapi.api.model.command.impl.FindOneCommand[\"filter\"])",
            "exceptionClass": "JsonMappingException"
        },
        {
            "message": "$in operator must have at least one value",
            "exceptionClass": "JsonApiException"
        }
    ]
}`

@ivansenic @amorton @tatu-at-datastax

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:
As discussed in the https://github.com/stargate/jsonapi/issues/350#issuecomment-1513166081 I pushed the implementation that fixes `errorCode` missing. We still need to agree on the handling of the cause and if we do want the error array to include the cause..

**Which issue(s) this PR fixes**:
Fixes #350

**Checklist**
- [x] Agree on cause handling

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/JsonApiException.java [hunk 1]
```diff
@@ -59,6 +56,12 @@ public CommandResult get() {
     }
   }
 
+  public CommandResult.Error getCommandResultError(String message) {
+    Map<String, Object> fields =
+        Map.of("errorCode", errorCode.name(), "exceptionClass", this.getClass().getSimpleName());
```
Comment (ivansenic) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/JsonApiException.java:61]: the `JsonApiException` was not including the `exceptionClass` before so I added it, I guess this is also helpful information..

**Review by maheshrajamani — APPROVED** [review]

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:
