### PR TITLE
Default vector search function name to cosine.

### LINKED ISSUE #483: Cannot `createCollection()` with vector option without sending similarity function
Sending the following command:

```
{
  createCollection: { name: 'vector', options: { vector: { size: 2 } } }
}
```

results in the following error:

```
Command "createCollection" failed with the following errors: [{"message":"INVALID_ARGUMENT: Similarity function NULL was not recognized for index null. Valid values are: EUCLIDEAN, DOT_PRODUCT, COSINE","exceptionClass":"StatusRuntimeException"}]
```

Ideally, `function` would default to 'cosine'.

### PR DESCRIPTION
**Pull request by maheshrajamani**
**What this PR does**:
Fixed to use default vector search function name to cosine.
**Which issue(s) this PR fixes**:
Fixes #483 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/model/impl/CreateCollectionCommandResolver.java [hunk 1]
```diff
@@ -41,7 +41,9 @@ public Operation resolveCommand(CommandContext ctx, CreateCollectionCommand comm
           ctx,
           command.name(),
           command.options().vector().size(),
-          command.options().vector().function());
+          command.options().vector().function() == null
+              ? "cosine"
+              : command.options().vector().function());
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/resolver/model/impl/CreateCollectionCommandResolver.java:46]: This could alternatively be done in `CreatoCollectionCommand.Option` record Constructor I think, converting `null` into "cosine" I think.

**Review by tatu-at-datastax — APPROVED** [review]
LGTM

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:
